name: CI
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      # - run: npm test
  publish:
    name: Publish to Docker
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Create and publish to Docker Hub
      uses: hannes-hochreiner/gha-publish-on-docker-hub@v1.4.0
      with:
        docker-user-name: ${{ secrets.DOCKER_USER }}
        docker-token: ${{ secrets.DOCKER_TOKEN }}
      id: publish
    - name: Call container updater
      uses: hannes-hochreiner/gha-authorized-request@v1.0.0
      with:
        auth0-domain: ${{ secrets.AUTH0_DOMAIN }}
        auth0-client-id: ${{ secrets.AUTH0_CLIENT_ID }}
        auth0-client-secret: ${{ secrets.AUTH0_CLIENT_SECRET }}
        auth0-audience: ${{ secrets.AUTH0_AUDIENCE }}
        data: ${{ steps.publish.outputs.images }}
        url: ${{ secrets.UPDATER_URL }}
